name: devops-sample-django-app

services:
  django:
    image: devops-sample-django-app
    build: .
    restart: always
    command: sh -c "python3 manage.py migrate && uwsgi --http 0.0.0.0:8000 --wsgi-file ./parrotsite/wsgi.py"
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: app
      DJANGO_DB_USER: worker
      DJANGO_DB_PASS: worker
      DJANGO_DB_PORT: "5432"
      DJANGO_DEBUG: "False"

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: worker
      POSTGRES_DB: app
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
